#!/bin/sh
cp ../j_swing_tile_set/other_sets.png ./game-headed/jbg/assets/territory/territory_tile_set.png
cp ../j_swing_tile_set/frontline_icon.png ./game-headed/jbg/assets/territory/
cp ../j_swing_tile_set/jbg_turnnews_banner.png game-headed/jbg/assets/turnnews/turnnews_banner.png
cp ../j_swing_tile_set/jbg_turnnews_bkgnd.png game-headed/jbg/assets/turnnews/turnnews_bkgnd.png
cp ../j_swing_tile_set/jbg_mobilization.png game-headed/jbg/assets/turnnews/jbg_mobilization.png
cp ../j_swing_tile_set/jbg_airop.png game-headed/jbg/assets/turnnews/jbg_airop.png
cp ../j_swing_tile_set/jbg_airop2.png game-headed/jbg/assets/turnnews/jbg_airop2.png
cp ../j_swing_tile_set/jbg_airop3.png game-headed/jbg/assets/turnnews/jbg_airop3.png
cp ../j_swing_tile_set/jbg_airop4.png game-headed/jbg/assets/turnnews/jbg_airop4.png
cp ../j_swing_tile_set/jbg_airbomb.png game-headed/jbg/assets/turnnews/jbg_airbomb.png
cp ../j_swing_tile_set/jbg_airbomb2.png game-headed/jbg/assets/turnnews/jbg_airbomb2.png
cp ../j_swing_tile_set/jbg_airbomb3.png game-headed/jbg/assets/turnnews/jbg_airbomb3.png
cp ../j_swing_tile_set/jbg_airbomb4.png game-headed/jbg/assets/turnnews/jbg_airbomb4.png
cp ../j_swing_tile_set/jbg_seaop.png game-headed/jbg/assets/turnnews/jbg_seaop.png
cp ../j_swing_tile_set/jbg_seaop2.png game-headed/jbg/assets/turnnews/jbg_seaop2.png
cp ../j_swing_tile_set/jbg_seaop3.png game-headed/jbg/assets/turnnews/jbg_seaop3.png
cp ../j_swing_tile_set/jbg_seaop4.png game-headed/jbg/assets/turnnews/jbg_seaop4.png
cp ../j_swing_tile_set/jbg_seaop_failure.png game-headed/jbg/assets/turnnews/jbg_seaop_failure.png
cp ../j_swing_tile_set/jbg_seaop_failure2.png game-headed/jbg/assets/turnnews/jbg_seaop_failure2.png
cp ../j_swing_tile_set/jbg_seaop_failure3.png game-headed/jbg/assets/turnnews/jbg_seaop_failure3.png
cp ../j_swing_tile_set/jbg_seaop_failure4.png game-headed/jbg/assets/turnnews/jbg_seaop_failure4.png
cp ../j_swing_tile_set/jbg_sea_airop.png game-headed/jbg/assets/turnnews/jbg_sea_airop.png
cp ../j_swing_tile_set/jbg_sea_airop2.png game-headed/jbg/assets/turnnews/jbg_sea_airop2.png
cp ../j_swing_tile_set/jbg_sea_airop3.png game-headed/jbg/assets/turnnews/jbg_sea_airop3.png
cp ../j_swing_tile_set/jbg_sea_airop4.png game-headed/jbg/assets/turnnews/jbg_sea_airop4.png
cp ../j_swing_tile_set/jbg_sea_airbomb.png game-headed/jbg/assets/turnnews/jbg_sea_airbomb.png
cp ../j_swing_tile_set/jbg_sea_airbomb2.png game-headed/jbg/assets/turnnews/jbg_sea_airbomb2.png
cp ../j_swing_tile_set/jbg_sea_airbomb3.png game-headed/jbg/assets/turnnews/jbg_sea_airbomb3.png
cp ../j_swing_tile_set/jbg_sea_airbomb4.png game-headed/jbg/assets/turnnews/jbg_sea_airbomb4.png
cp ../j_swing_tile_set/jbg_amphib_op.png game-headed/jbg/assets/turnnews/jbg_amphib_op.png
cp ../j_swing_tile_set/jbg_amphib_op2.png game-headed/jbg/assets/turnnews/jbg_amphib_op2.png
cp ../j_swing_tile_set/jbg_amphib_op3.png game-headed/jbg/assets/turnnews/jbg_amphib_op3.png
cp ../j_swing_tile_set/jbg_amphib_op4.png game-headed/jbg/assets/turnnews/jbg_amphib_op4.png

